// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.s2.simbadtest;

import java.awt.image.BufferedImage;


public class Data {
	public boolean isTarget; 
	public BufferedImage photo;
	
	Data() {
		 isTarget = true;
	}
}
