// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.s2.simbadtest;

public class Database  {

	public Data[][] database;
	
	Database (int width,int height) {
		database = new Data[width][height];
		for (int i = 0; i < width; i++) {
			for (int j = 0; j < height; j++) {
				database[i][j] = new Data();
				} 
			}
		}
	}
	
