// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.s2.simbadtest;

import simbad.gui.*;

import simbad.sim.*;
import javax.vecmath.Vector3d;


public class Main {
	public static EnvironmentDescription environment;

	public static void main(String[] args) {
	    CentralStation cs = new CentralStation();
        
		// request antialising so that diagonal lines are not "stairy"
        System.setProperty("j3d.implicitAntialiasing", "true");
        
        // creation of the environment containing all obstacles and robots
        environment = new ExampleEnvironment();
        environment.add(cs.rover.robot);
      
        
        // here we create an instance of the whole Simbad simulator and we assign the newly created environment 
        Simbad frame = new Simbad(environment, false);
        frame.update(frame.getGraphics());
        cs.initiate();
    
    	}
	}
	

