// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.s2.simbadtest;

import nl.vu.cs.s2.simbadtest.Subject;

public abstract class Observer {

	protected Subject subject;

	public abstract void update();
};
