// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVUSystem;

import RootElement.ROVUSystem.Data;
import RootElement.ROVUSystem.Database;
import RootElement.ROVUSystem.RoverFactory;
import RootElement.ROVUSystem.Singleton;
import RootElement.ROVUSystem.Subject;

public class CentralStation extends Singleton {

	private Database mapDatabase;
	private boolean missionComplete = false;
	//private undefined path;
	public Data[] data;
	public RoverFactory roverfactory;

	private void createRover() {
		
	}

	private void getData() {
		
	}

	private void storeData() {
		
	}

	private void createPath() {
		
	}

	private void instructRover() {
		
	}
	
}
