// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVUSystem;

public class Data {

	public boolean visited, isObstacle, isTarget = false;
	//public undefined photos;
	
}
