// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVUSystem;

import RootElement.ROVUSystem.Singleton;

public class Database extends Singleton {

	public Data[][] database;
	
	Database() {
		//database = new Data[WIDTH][HEIGHT];
	}
	
}
