// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVUSystem;

public class Main {

	public static void main(String[] args) {
		Singleton centralStation = Singleton.getCentralStationInstance();
		Singleton database = Singleton.getDatabaseInstance();
		Singleton scoutingRover = Singleton.getScoutingRoverInstance();
	}
	
}
