// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVUSystem;

import RootElement.ROVUSystem.Observer;

public abstract class Rover extends Observer {

	public int direction, state = 0;
}
