// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVUSystem;

import RootElement.ROVUSystem.Rover;

public class RoverFactory {

//	public Rover getRover(undefined type) {
//	}
	
}