// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVUSystem;

import RootElement.ROVUSystem.Rover;
import RootElement.ROVUSystem.Singleton;

class ScoutingRover extends Rover {
	public ScoutingRover(Subject subject) {
		this.subject = subject;
		subject.attach(this);
	}

	private void detectObstacles() {
	}

	@Override
	public void update() {
		if (this.subject.getState() == 0) {
			// MAP
		} else {
			// WAIT
		}
	}
};
