// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVUSystem;

public class Singleton {

	private static Singleton centralStationInstance = new Singleton();
	private static Singleton databaseInstance = new Singleton();
	private static Singleton scoutingRoverInstance = new Singleton();

	private Singleton(){
		
	}
	
	public static Singleton getCentralStationInstance() {
		return centralStationInstance;
	}
	
	public static Singleton getDatabaseInstance() {
		return databaseInstance;
	}
	
	public static Singleton getScoutingRoverInstance() {
		return scoutingRoverInstance;
	}

}
