// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVUSystem;

import java.util.ArrayList;
import java.util.List;

import RootElement.ROVUSystem.Observer;

public abstract class Subject {
	
	private List<Observer> observers = new ArrayList<Observer>();
	private int state;

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
		this.notifyAllObservers();
	}

	public void attach(Observer observer) {
		this.observers.add(observer);
	}

	public void detach(Observer observer) {
		this.observers.remove(observers.indexOf(observer));
	}

	public void notifyAllObservers() {
		for (Observer observer : this.observers) {
			observer.update();
		}
	}
};
