// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU System;

import RootElement.ROVU System.Data;
import RootElement.ROVU System.Database;
import RootElement.ROVU System.RoverFactory;
import RootElement.ROVU System.Singleton;
import RootElement.ROVU System.Subject;


/************************************************************/
/**
 * 
 */
public class CentralStation extends Singleton
 {
    			/**
    			 * 
    			 */
    			private Database mapDatabase;
    			/**
    			 * 
    			 */
    			private boolean missionComplete =false;
    			/**
    			 * 
    			 */
    			private undefined path;
    			/**
    			 * 
    			 */
    			public Data[] data;
    			/**
    			 * 
    			 */
    			public RoverFactory roverfactory;
	
	/**
	 * 
	 */
	private void createRover() {
	}
	
	/**
	 * 
	 */
	private void getData() {
	}
	
	/**
	 * 
	 */
	private void storeData() {
	}
	
	/**
	 * 
	 */
	private void createPath() {
	}
	
	/**
	 * 
	 */
	private void instructRover() {
	}
};
