// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU System;

import RootElement.ROVU System.Singleton;


/************************************************************/
/**
 * 
 */
public class Database extends Singleton
 {
    			/**
    			 * 
    			 */
    			public undefined database;
};
