// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU System;

import RootElement.ROVU System.Data.BufferedImage[];


/************************************************************/
/**
 * 
 */
public class Data {
    			/**
    			 * 
    			 */
    			public boolean visited =false;
    			/**
    			 * 
    			 */
    			public boolean isObstacle =false;
    			/**
    			 * 
    			 */
    			public BufferedImage[] photos;
    			/**
    			 * 
    			 */
    			public boolean isTarget =false;
};
