// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU System;

import RootElement.ROVU System.DataSamplingRover.String;
import RootElement.ROVU System.Rover;


/************************************************************/
/**
 * 
 */
public class DataSamplingRover extends Rover
 {
    			/**
    			 * 
    			 */
    			public String name;
	
	/**
	 * 
	 */
	public void takePhoto() {
	}
};
