// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU System;

import RootElement.Subject;


/************************************************************/
/**
 * 
 */
public abstract class Observer {
    			/**
    			 * 
    			 */
    			public Subject subject;
	
	/**
	 * 
	 */
	public abstract void update() ;
};
