// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU System;

import RootElement.ROVU System.CentralStation;


/************************************************************/
/**
 * 
 */
public class Operator extends CentralStation
 {
	
	/**
	 * 
	 */
	public void start() {
	}
	
	/**
	 * 
	 */
	public void stop() {
	}
};
