// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU System;

import RootElement.ROVU System.Rover;


/************************************************************/
/**
 * 
 */
public class RoverFactory {
	
	/**
	 * 
	 * @return Rover 
	 * @param type 
	 */
	public Rover getRover(undefined type) {
	}
};
