// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU System;

import RootElement.ROVU System.Observer;


/************************************************************/
/**
 * 
 */
public abstract class Rover extends Observer
 {
    			/**
    			 * 
    			 */
    			public int direction =0;
    			/**
    			 * 
    			 */
    			public int state =0;
};
