// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU System;

import RootElement.ROVU System.Rover;
import RootElement.ROVU System.Singleton;


/************************************************************/
/**
 * 
 */
public class ScoutingRover extends Rover
 {
	
	/**
	 * 
	 */
	private void detectObstacles() {
	}
};
