// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU System;



/************************************************************/
/**
 * 
 */
public class Singleton {
    			/**
    			 * 
    			 */
    			public static undefined uniqueInstance;
    			/**
    			 * 
    			 */
    			public undefined singletonData;
	
	/**
	 * return uniqueInstance
	 */
	public static void instance() {
	}
	
	/**
	 * 
	 */
	public void singletonOperation() {
	}
	
	/**
	 * 
	 */
	public void getSingletonData() {
	}
};
