// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ROVU System;

import RootElement.ArrayList;
import RootElement.ROVU System.Observer;


/************************************************************/
/**
 * 
 */
public abstract class Subject {
    			/**
    			 * 
    			 */
    			private ArrayList observers;
    			/**
    			 * 
    			 */
    			private int state;
	
	/**
	 * 
	 * @return state 
	 */
	public int getState() {
	}
	
	/**
	 * 
	 * @param state 
	 */
	public void setState(int state) {
	}
	
	/**
	 * 
	 * @param observer 
	 */
	public void attach(Observer observer) {
	}
	
	/**
	 * 
	 * @param observer 
	 */
	public void detach(Observer observer) {
	}
	
	/**
	 * 
	 */
	public void notifyAllObservers() {
	}
};
